<x-filament-panels::page>

    <x-core.report-content  listner="employee_activity_report">
        @slot('pageHeader')
            <div class="grid grid-cols-3 items-center p-2 rounded-md align-middle border ">
                <div>
                    {!! trans('lang.statement_date', ['from' => $hire_date_from, 'to' => $hire_date_to!='all'?$hire_date_to:now()->format('Y/m/d') ]) !!}
                </div>
                <div class="font-bold">
                    {{trans('HR/lang.reports.employees')}}
                </div>
                <div>
                </div>
            </div>
        @endslot
        @slot('tableHeader')
            @if(valueInArray('owner',$attr))
                <th>
                    {{trans('lang.owner')}}
                </th>
            @endif
            @if(valueInArray('user',$attr))
                <th>
                    {{trans('lang.user')}}
                </th>
            @endif
            @if(valueInArray('name',$attr))
                <th>
                    {{trans('lang.name')}}
                </th>
            @endif
                @if(valueInArray('email',$attr))
                    <th>
                        {{trans('lang.email')}}
                    </th>
                @endif
                @if(valueInArray('phone',$attr))
                    <th>
                        {{trans('lang.phone')}}
                    </th>
                @endif
                @if(valueInArray('gender',$attr))
                    <th>
                        {{trans('lang.gender')}}
                    </th>
                @endif
                @if(valueInArray('identity_type_id',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif
                @if(valueInArray('nationality',$attr))
                    <th>
                        {{trans('lang.nationality')}}
                    </th>
                @endif

        @endslot
        @slot('tableContent')
            @foreach($data as $dt)
                <tr>
                    @if(valueInArray('owner',$attr))
                        <td>
                            {{$dt->ownerable->name??''}}
                        </td>
                    @endif
                    @if(valueInArray('user',$attr))
                        <td>
                            {{$dt->user->name??''}}
                        </td>
                    @endif
                    @if(valueInArray('employee.name',$attr))
                        <td>
                            {{$dt->employee->name??''}}
                        </td>
                    @endif
                    @if(valueInArray('date',$attr))
                        <td>
                            {{\Carbon\Carbon::parse($dt->created_at)->format('Y-m-d')}}
                        </td>
                    @endif
                    @if(valueInArray('note',$attr))
                        <td>
                            {{$dt->note}}
                        </td>
                    @endif
                </tr>
            @endforeach
        @endslot
        @slot('tableFooter')

        @endslot
        @slot('pageFooter')

        @endslot
    </x-core.report-content>

</x-filament-panels::page>
