<?php

namespace App\Models\HR;

use App\Models\Logistic\Branch;
use App\Models\Settings\Currency;
use App\Traits\Core\HasUser;
use App\Traits\Core\Ownerable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class EmployeeActivity extends Model
{
    use HasFactory;
    use HasUser;
    use Ownerable, SoftDeletes;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->currency_id = Employee::find($model->employee_id)?->currency_id??1;
        });
    }

    public function employee():BelongsTo{
        return $this->belongsTo(Employee::class)->withTrashed();
    }
    public function currency():BelongsTo{
        return $this->belongsTo(Currency::class)->withTrashed();
    }
    public function branch(): BelongsTo{
        return $this->belongsTo(Branch::class)->withTrashed();
    }

    public static function getTypes():array{
        return [
          'punish'=>trans('lang.punishment'),
          'bonus'=>trans('lang.bonus'),
          'absence'=>trans('lang.absence'),
          'advance'=>trans('lang.advance'),
          'overtime'=>trans('lang.overtime'),
        ];
    }

    public function scopePunish($query){
        return $query->where('type','punish');
    }
    public function scopeBonus($query){
        return $query->where('type','bonus');
    }
    public function scopeAdvance($query){
        return $query->where('type','advance');
    }
    public function scopeOvertime($query){
        return $query->where('type','overtime');
    }
    public function scopeAbsence($query){
        return $query->where('type','absence');
    }


}
