<?php

namespace App\Models\HR;

use App\Models\Logistic\Branch;
use App\Models\Settings\Currency;
use App\Traits\Core\HasUser;
use App\Traits\Core\Ownerable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class EmployeeSalary extends Model
{
    use HasFactory;
    use HasUser;
    use Ownerable;
    protected $appends = [
        'owner_name',
        'user_name',
        'employee_name',
    ];
    public function getOwnerNameAttribute()
    {
        return $this->ownerable?->name;
    }
    public function getUserNameAttribute()
    {
        return $this->user?->name;
    }
    public function getEmployeeNameAttribute()
    {
        return $this->employee?->name;
    }

    public static function getLabels(){
        return [
            'owner_name' => trans('lang.owner'),
            'user_name'=>trans('user'),
            'employee_name'=>trans('lang.employee'),
            'status'=>trans('lang.status'),
            'from'=>trans('lang.from'),
            'to'=>trans('lang.to'),
            'date'=>trans('lang.date'),
            'note'=>trans('lang.note'),
        ];

    }
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->currency_id = Employee::find($model->employee_id)?->currency_id??1;
            unset($model['lastSalaryDate']);
             $model->currency_rate = getCurrencyRate($model->currency_id);
        });
        self::updating(function ($model) {
            unset($model['lastSalaryDate']);
        });

    }

    public function employee():BelongsTo{
        return $this->belongsTo(Employee::class)->withTrashed();
    }
    public function currency():BelongsTo{
        return $this->belongsTo(Currency::class)->withTrashed();
    }
    public function branch(): BelongsTo{
        return $this->belongsTo(Branch::class)->withTrashed();
    }

    public function getDollarAmountAttribute():float{
        return $this->amount / ($this->currency_rate?? 1);
    }

}
