<?php

namespace App\Models\HR;

use App\Models\Logistic\Branch;
use App\Models\Settings\Currency;
use App\Traits\Core\HasUser;
use App\Traits\Core\Ownerable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class EmployeeActivity extends Model
{
    use HasFactory;
    use HasUser;
    use Ownerable, SoftDeletes;

    // appends
    protected $appends = [
        'owner_name',
        'user_name',
        'employee_name',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->currency_id = Employee::find($model->employee_id)?->currency_id??1;
        });
    }

    public function employee():BelongsTo{
        return $this->belongsTo(Employee::class)->withTrashed();
    }
    public function currency():BelongsTo{
        return $this->belongsTo(Currency::class)->withTrashed();
    }
    public function branch(): BelongsTo{
        return $this->belongsTo(Branch::class)->withTrashed();
    }

    public static function getTypes():array{
        return [
          'punish'=>trans('lang.punishment'),
          'bonus'=>trans('lang.bonus'),
          'absence'=>trans('lang.absence'),
          'advance'=>trans('lang.advance'),
          'overtime'=>trans('lang.overtime'),
        ];
    }
    public static function getLabels():array{
        return [
            'owner_name' => trans('lang.owner'),
            'user_name'=>trans('user'),
            'employee_name'=>trans('lang.employee'),
            'type'=>trans('lang.type'),
            'amount'=>trans('lang.amount'),
            'currency_rate'=>trans('lang.currency_rate'),
            'date'=>trans('lang.date'),
            'note'=>trans('lang.note'),
        ];
    }

    public function scopePunish($query){
        return $query->where('type','punish');
    }
    public function scopeBonus($query){
        return $query->where('type','bonus');
    }
    public function scopeAdvance($query){
        return $query->where('type','advance');
    }
    public function scopeOvertime($query){
        return $query->where('type','overtime');
    }
    public function scopeAbsence($query){
        return $query->where('type','absence');
    }

    // attributes owner_name, user_name, employee_name
    public function getOwnerNameAttribute()
    {
        return $this->ownerable?->name;
    }
    public function getUserNameAttribute()
    {
        return $this->user?->name;
    }
    public function getEmployeeNameAttribute()
    {
        return $this->employee?->name;
    }



}
