<?php

namespace App\Traits;

use Filament\Tables\Table;

trait TranslatableTable
{
    public function table(Table $table): Table
    {
        $columns = [];
        foreach (parent::table($table)->getColumns() as $key =>$column){
            $columns[] = $column->label(trans('lang.'.$key));
        }
        return parent::table($table)->columns($columns); // TODO: Change the autogenerated stub
    }
}
