<?php

namespace App\Models\Logistic;

use App\Traits\Core\HasUser;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ItemTransactionCode extends Model
{
    use HasFactory;
    use HasUser;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function (Model $model){
            $model->status_date = now();
        });
        self::updating(function (Model $model){
            $model->status_date = now();
        });
    }

    public function itemTransactionDetail():BelongsTo{
        return $this->belongsTo(ItemTransactionDetail::class);
    }

    public function getFromableAttribute(){
        return $this->itemTransactionDetail->invoice;
    }

}
